    Finished release [optimized] target(s) in 0.01s
     Running `target/release/tester ../build/ahc008-a-3`
UR DL RU RD LRL LR D D R LD L 
RR LR LU RL URD LD L R L LU R 
UL LD DR RL LDD LL L R L LR R 
UL LU DL DR DRL DL D D D LD U 
RD LR LL LR DDD RL D U U UL D 
DR DL UD RU DDD DR D U U LR U 
RU LR RD LR URL DD R D U LR R 
UR LR LR DU DLL LD D D U LD U 
DU LL DU LD DUR LR D D L UD L 
RD DD RU RR URR LD U U U LR U 
UL DR UU LU DDR LU L U U LU U 
DU DR LR RL DDD LL R L L LU R 
UD DU RR DD DUU LL L U U LD R 
LL RD RR LU DRL LD D R U LD R 
DU RD RL LR LUL UU L D R UD R 
UD RD RL UU LDL LU U L U UR D 
RR RR LD RU DDU LR R U U LR U 
DL DL UR LL LLL DD L R D LU R 
LD RL LD RU DUR LU L L U LD U 
RR RR LU UR URL LR R L D LL L 
UL DR DD RR DLL LD R D L LD L 
DR RU LU DL DDL LU U U L LD D 
UD RU RU DL RUU DR D R U LU L 
UD UR DU LD LDU RD U L D UR D 
UL UR LL RU UDU RD L U R UL R 
RR UL LL LR RLR RR D U R LU L 
RR UL LR LL DLR UL D D L LU D 
LR RD LR DU DDU UU D D R UU L 
UR UL LD LR LRL RU R R U LU L 
LU UU DL UL LUD DL U L D LD D 
LD RD DR UD DRL DR R D U LR L 
UR UL RL LD UDU RU R U D UR R 
LL LD UD UU DUD RR R D R UL R 
UL UR LR DD DRL DR U R U LR L 
UD LL DL DR DLL RU R R R LU L 
RR LR RD UD ULL RU R D L DU D 
DU LR RL RR RUU DD L R L LR U 
LD LD RD RL DRR RR L R L DR R 
DU UU UD RR DDD RL L D U LR D 
UU UU UR RL UUL RL D L R LR L 
RL UL DR UU DUD RL L L D LR R 
RR RL LU RL RUD RR L D U LR R 
DD RU UR LU RRR LU L U R LU U 
UL RR RR DL DUL LR R R L DL L 
UR UR UR RU UDD UL D L R LD L 
RR UL RL DD LRL LL L D L RL D 
LL RD LU DD LUU UR R R R RU R 
DU RU LD UU LUR UR R R R RL U 
DD RD DL DR LUL DL L U R UU U 
RR RU LR RL RLD DD U L R RU D 
LR RR DR UD RLD RU D D U DR D 
DR RU DL UR ULL RR L D D RL R 
LU UL LR DU DUU DU L L L UR L 
RR UR RL LL LUR DL U R U RR U 
DD LR RL LR LRD DR D U U UR D 
UU LR UD UL UDU L terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 1) >= this->size() (which is 1)
Your program has terminated unexpectedly on turn 57
Score = 0
