    Finished release [optimized] target(s) in 0.01s
     Running `target/release/tester ../build/ahc008-a-3`
LD UL LL R UR RL LL LLD L RU 
DL RD LR R UD DD LR LDU U UL 
DL LU LR L UU UL UU RLD D RD 
DU RL LD R UL RL UR DRD D UR 
DR DU DR L RR LL LU UDU D LU 
LR RU DR U UL RL LR LUR L UL 
DD LR LL U RR RL LD LRU R UL 
DL LU LR U UU RR LR LDD D RD 
DR UD LU R LD UR DL DUR D UU 
LD LU LL R RU LU RD LDU R RL 
LL DL LD D RR UL LU RUL L UL 
LD LR UL R RU LU DL DUU R RU 
LR UR LL R RR DL UL DUR D RR 
LL RD UD U RU DR UL RRD D LL 
DU UR UL R UL LR RD RLR U RU 
DR LU UL D UL UD UD UUD D DL 
DR LL LD L RR DL DU RRU U DD 
DL UL LU R RU DL DR ULL D RD 
DU UD RR L UR DD UR RUD D UD 
DR LL RU R RD UR LR RDR R UU 
DL LL UU L RD DL UU LUU U UR 
DR RL UU D RR DU RL DUL D RD 
LR UD UR D UL RL DD DDL D UR 
DU UR UU D UD RD LR URR U RD 
DD DU RR U UR RL LU URD D RU 
LU DR RL U UL DD UL LDL L RD 
DD LD RR U RU UU UU URR R UR 
UR UD UR U UL RL UL URL U RD 
LU LL UR D UR LR DD LRL L UR 
DL LU LU R UD DR UR LDL U RD 
LL DD DL U UU UD DR LLU D RU 
LR UU RR R UL RD UD UUU D RR 
DU LR DR L UL RU UD LDR R LL 
DR DR DR R RR LR LU UDU D LL 
DU RR RR D RD DU DU RUR L LR 
DL UU DD U RD LR LU RRD D LL 
RD RL DR R UR UL DR RDL L LR 
RD LR RD L LU RU DR LUD L LR 
RL LL DD L UR LR UD DRD R LL 
DD RD RU D LL UU DD RLL L LR 
RD DL DR L LU UU UU LLR L LR 
RL LL DR R LL LL DD RLU L LR 
RL DU DU R DU RD DD UUL L LD 
RL LR LL R DR UL DU LUR U LD 
RU LL RL L LR RR LR URD D LD 
DL UD DL D DL RL DL ULD U UL 
DL DL RU D LD DD UD DLL U UU 
DU UL DU R UL DL LL RRR L UR 
DR UD DL L LD UL LU DLR L UR 
RL UD RU D UU RR UU RRD L UL 
DU LD RD L DD LL RD LRD U LL 
DR UD RR R UD DR DD LDR D LU 
DR RR RL R UR UR LL LUL U LU 
RR RR RU L LL UU RU LRR R DR 
RR DD DU U LD DU DL DUU U LR 
RU UR RD D UU LD LR DLR L LR 
DU RR U terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 1) >= this->size() (which is 1)
Your program has terminated unexpectedly on turn 58
Score = 0
